### ISSUE TITLE
Try xresnet with PReLU or LeakyReLU

### ISSUE THREAD

**Issue by JoshVarty** [JoshVarty/AudioTagging#29]
This kernel seemed to improve a lot when it changed to using a LeakyReLU. It's also a very small network which is interesting.

**Comment by JoshVarty** [comment]
After upgrading to `1.0.52` I can't seem to use xresnet anymore :(

```
Traceback (most recent call last):
  File "trainAll.py", line 129, in <module>
    learn = cnn_learner(data, models.xresnet152, pretrained=False, metrics=[f_score]).mixup(stack_y=False)
  File "/home/josh/anaconda3/envs/ml/lib/python3.6/site-packages/fastai/vision/learner.py", line 97, in cnn_learner
    split_on=split_on, bn_final=bn_final, concat_pool=concat_pool)
  File "/home/josh/anaconda3/envs/ml/lib/python3.6/site-packages/fastai/vision/learner.py", line 83, in create_cnn_model
    body = create_body(base_arch, pretrained, cut)
  File "/home/josh/anaconda3/envs/ml/lib/python3.6/site-packages/fastai/vision/learner.py", line 55, in create_body
    model = arch(pretrained)
```

Investigating here: https://github.com/fastai/fastai/issues/1822

**Comment by JoshVarty** [comment]
Baseline ResNet with ReLU: `0.8438248`
With PReLU: `0.8438683`/`0.84805405`
Leaky ReLU: `0.8416822`/`0.8444001`

**Comment by JoshVarty** [comment]
I don't really see a difference beyond noise from using other ReLUs.
